package com.example.motels.dto.mapper;

import com.example.motels.dto.request.CreateRoomCategoryRequest;
import com.example.motels.dto.request.UpdateRoomCategoryRequest;
import com.example.motels.dto.response.RoomCategoryResponse;
import com.example.motels.model.RoomCategory;
import org.mapstruct.*;

import java.util.List;

/**
 * MapStruct mapper for RoomCategory entity and DTOs.
 * 
 * MapStruct generates implementation at compile-time, providing:
 * - Type-safe mapping
 * - Zero runtime overhead
 * - Compile-time error detection
 * - No reflection
 * 
 * Theory: Why MapStruct?
 * 
 * 1. Compile-Time Generation:
 *    - Mapper implementation generated during compilation
 *    - No runtime reflection or proxy objects
 *    - Performance equivalent to hand-written code
 * 
 * 2. Type Safety:
 *    - Compilation fails if field types don't match
 *    - Catches mapping errors at build time, not runtime
 *    - Refactoring-safe: IDE can track field usage
 * 
 * 3. Maintainability:
 *    - No boilerplate getter/setter code
 *    - Single source of truth for mappings
 *    - Easy to customize with @Mapping annotations
 * 
 * 4. Integration:
 *    - Works with Spring's dependency injection
 *    - Can use other Spring beans in mappings
 *    - Supports complex nested object mapping
 * 
 * Usage:
 * - @Mapper(componentModel = "spring") makes it a Spring bean
 * - @Mapping annotations customize field mappings
 * - @MappingTarget updates existing entity
 * - ignore = true skips fields (like auto-generated IDs)
 */
@Mapper(componentModel = "spring")
public interface RoomCategoryMapper {
    
    /**
     * Convert entity to response DTO.
     * Used when returning data to clients.
     * 
     * All fields are mapped automatically by name matching.
     */
    RoomCategoryResponse toResponse(RoomCategory entity);
    
    /**
     * Convert list of entities to list of response DTOs.
     * Useful for pagination and list endpoints.
     */
    List<RoomCategoryResponse> toResponseList(List<RoomCategory> entities);
    
    /**
     * Convert create request DTO to entity.
     * Used when creating new room categories.
     * 
     * Ignored fields:
     * - motelRoomCategoryId: Auto-generated by database
     * - createdAt: Set by @CreationTimestamp
     * - updatedAt: Set by @UpdateTimestamp
     * - deletedAt: Not set on creation
     */
    @Mapping(target = "motelRoomCategoryId", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    RoomCategory toEntity(CreateRoomCategoryRequest request);
    
    /**
     * Update existing entity from update request DTO.
     * Only updates fields that are present in the request.
     * 
     * @MappingTarget: Modifies the existing entity in-place
     * 
     * Ignored fields:
     * - motelRoomCategoryId: Cannot change primary key
     * - motelChainId: Cannot change after creation
     * - motelId: Cannot change after creation
     * - createdAt: Never changes
     * - deletedAt: Managed separately
     * 
     * NullValuePropertyMappingStrategy.IGNORE:
     * - Only updates non-null fields from request
     * - Allows partial updates (PATCH-like behavior)
     * - Null values in request don't overwrite existing data
     */
    @Mapping(target = "motelRoomCategoryId", ignore = true)
    @Mapping(target = "motelChainId", ignore = true)
    @Mapping(target = "motelId", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", expression = "java(java.time.LocalDateTime.now())")
    @Mapping(target = "deletedAt", ignore = true)
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void updateEntityFromRequest(UpdateRoomCategoryRequest request, @MappingTarget RoomCategory entity);
}
