version: '3.8'

services:
  motel-api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: motel-api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/api-gateway-dashboard.json
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
