version: '3.8'

services:
  motel-api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: motel-api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    networks:
      - monitoring

networks:
  monitoring:
